---
disabled_rules: # rule identifiers to exclude from running
  - line_length
#  - trailing_newline
  - trailing_whitespace
  - multiple_closures_with_trailing_closure
  - force_cast
  - identifier_name
#  - comma
#  - control_statement
opt_in_rules: # some rules are only opt-in
  - empty_count
  - missing_docs
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - Sources
  - Tests
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
#force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
function_parameter_count:
  warning: 6
  error: 10
# rules that have both warning and error levels, can set just the warning level
# implicitly
#line_length: 110
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 40
  excluded: iPhone # excluded via string
identifier_name:
  min_length: # only min_length
    error: 3 # only warning
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
reporter: # reporter type (xcode, json, csv, checkstyle)
  - xcode
  - json
