import SwiftUI

protocol AdaptiveColors {
  var bgBasicLevel1Default: Color { get }
  var bgBasicLevel1Hovered: Color { get }
  var bgBasicLevel1Pressed: Color { get }
  var bgBasicLevel2Default: Color { get }
  var bgBasicLevel2Hovered: Color { get }
  var bgBasicLevel2Pressed: Color { get }
  var bgBasicLevel3Default: Color { get }
  var bgBasicLevel3Hovered: Color { get }
  var bgBasicLevel3Pressed: Color { get }
  var bgBasicTransparentFullDefault: Color { get }
  var bgBasicTransparentSemiDefault: Color { get }
  var bgBasicTransparentHovered: Color { get }
  var bgBasicTransparentPressed: Color { get }
  var onBgBasicEmphasis100Default: Color { get }
  var onBgBasicEmphasis100Hovered: Color { get }
  var onBgBasicEmphasis100Pressed: Color { get }
  var onBgBasicEmphasis90Default: Color { get }
  var onBgBasicEmphasis90Hovered: Color { get }
  var onBgBasicEmphasis90Pressed: Color { get }
  var onBgBasicEmphasis80Default: Color { get }
  var onBgBasicEmphasis80Hovered: Color { get }
  var onBgBasicEmphasis80Pressed: Color { get }
  var onBgBasicEmphasis70Default: Color { get }
  var onBgBasicEmphasis70Hovered: Color { get }
  var onBgBasicEmphasis70Pressed: Color { get }
  var onBgBasicEmphasis60Default: Color { get }
  var onBgBasicEmphasis60Hovered: Color { get }
  var onBgBasicEmphasis60Pressed: Color { get }
  var onBgBasicEmphasis50Default: Color { get }
  var onBgBasicEmphasis50Hovered: Color { get }
  var onBgBasicEmphasis50Pressed: Color { get }
  var bgInvertedContrastMaxDefault: Color { get }
  var bgInvertedContrastMaxHovered: Color { get }
  var bgInvertedContrastMaxPressed: Color { get }
  var bgInvertedContrastHighDefault: Color { get }
  var bgInvertedContrastHighHovered: Color { get }
  var bgInvertedContrastHighPressed: Color { get }
  var bgInvertedContrastLowDefault: Color { get }
  var bgInvertedContrastLowHovered: Color { get }
  var bgInvertedContrastLowPressed: Color { get }
  var onBgInvertedDefault: Color { get }
  var onBgInvertedHovered: Color { get }
  var onBgInvertedPressed: Color { get }
  var onOriginDefault: Color { get }
  var onOriginHovered: Color { get }
  var onOriginPressed: Color { get }
  var originDefault: Color { get }
  var originHovered: Color { get }
  var originPressed: Color { get }
}
struct DeutscheBahnThemeColorScheme {
 let neutral: AdaptiveColors
 let brand: AdaptiveColors
 let informational: AdaptiveColors
 let warning: AdaptiveColors
 let successful: AdaptiveColors
 let critical: AdaptiveColors
 let yellow: AdaptiveColors
 let orange: AdaptiveColors
 let red: AdaptiveColors
 let pink: AdaptiveColors
 let violet: AdaptiveColors
 let blue: AdaptiveColors
 let cyan: AdaptiveColors
 let turquoise: AdaptiveColors
 let green: AdaptiveColors
}
@Observable
class NeutralColorsDark: AdaptiveColors {
var bgBasicLevel1Default = DBColors.neutral3
var bgBasicLevel1Hovered = DBColors.neutral4
var bgBasicLevel1Pressed = DBColors.neutral5
var bgBasicLevel2Default = DBColors.neutral2
var bgBasicLevel2Hovered = DBColors.neutral3
var bgBasicLevel2Pressed = DBColors.neutral4
var bgBasicLevel3Default = DBColors.neutral1
var bgBasicLevel3Hovered = DBColors.neutral2
var bgBasicLevel3Pressed = DBColors.neutral3
var bgBasicTransparentFullDefault = DBColors.neutral9.opacity(1)
var bgBasicTransparentSemiDefault = DBColors.neutral9.opacity(0.84)
var bgBasicTransparentHovered = DBColors.neutral9.opacity(0.76)
var bgBasicTransparentPressed = DBColors.neutral9.opacity(0.68)
var onBgBasicEmphasis100Default = DBColors.neutral12
var onBgBasicEmphasis100Hovered = DBColors.neutral11
var onBgBasicEmphasis100Pressed = DBColors.neutral10
var onBgBasicEmphasis90Default = DBColors.neutral10
var onBgBasicEmphasis90Hovered = DBColors.neutral9
var onBgBasicEmphasis90Pressed = DBColors.neutral8
var onBgBasicEmphasis80Default = DBColors.neutral9
var onBgBasicEmphasis80Hovered = DBColors.neutral8
var onBgBasicEmphasis80Pressed = DBColors.neutral7
var onBgBasicEmphasis70Default = DBColors.neutral8
var onBgBasicEmphasis70Hovered = DBColors.neutral7
var onBgBasicEmphasis70Pressed = DBColors.neutral6
var onBgBasicEmphasis60Default = DBColors.neutral6
var onBgBasicEmphasis60Hovered = DBColors.neutral5
var onBgBasicEmphasis60Pressed = DBColors.neutral4
var onBgBasicEmphasis50Default = DBColors.neutral5
var onBgBasicEmphasis50Hovered = DBColors.neutral4
var onBgBasicEmphasis50Pressed = DBColors.neutral3
var bgInvertedContrastMaxDefault = DBColors.neutral12
var bgInvertedContrastMaxHovered = DBColors.neutral11
var bgInvertedContrastMaxPressed = DBColors.neutral10
var bgInvertedContrastHighDefault = DBColors.neutral9
var bgInvertedContrastHighHovered = DBColors.neutral8
var bgInvertedContrastHighPressed = DBColors.neutral7
var bgInvertedContrastLowDefault = DBColors.neutral8
var bgInvertedContrastLowHovered = DBColors.neutral7
var bgInvertedContrastLowPressed = DBColors.neutral6
var onBgInvertedDefault = DBColors.neutral3
var onBgInvertedHovered = DBColors.neutral4
var onBgInvertedPressed = DBColors.neutral5
var onOriginDefault = DBColors.neutralOnOriginDefaultDark
var onOriginHovered = DBColors.neutralOnOriginHoveredDark
var onOriginPressed = DBColors.neutralOnOriginPressedDark
var originDefault = DBColors.neutralOriginDefaultDark
var originHovered = DBColors.neutralOriginHoveredDark
var originPressed = DBColors.neutralOriginPressedDark
}
@Observable
class BrandColorsDark: AdaptiveColors {
var bgBasicLevel1Default = DBColors.brand3
var bgBasicLevel1Hovered = DBColors.brand4
var bgBasicLevel1Pressed = DBColors.brand5
var bgBasicLevel2Default = DBColors.brand2
var bgBasicLevel2Hovered = DBColors.brand3
var bgBasicLevel2Pressed = DBColors.brand4
var bgBasicLevel3Default = DBColors.brand1
var bgBasicLevel3Hovered = DBColors.brand2
var bgBasicLevel3Pressed = DBColors.brand3
var bgBasicTransparentFullDefault = DBColors.brand9.opacity(1)
var bgBasicTransparentSemiDefault = DBColors.brand9.opacity(0.84)
var bgBasicTransparentHovered = DBColors.brand9.opacity(0.76)
var bgBasicTransparentPressed = DBColors.brand9.opacity(0.68)
var onBgBasicEmphasis100Default = DBColors.brand12
var onBgBasicEmphasis100Hovered = DBColors.brand11
var onBgBasicEmphasis100Pressed = DBColors.brand10
var onBgBasicEmphasis90Default = DBColors.brand10
var onBgBasicEmphasis90Hovered = DBColors.brand9
var onBgBasicEmphasis90Pressed = DBColors.brand8
var onBgBasicEmphasis80Default = DBColors.brand9
var onBgBasicEmphasis80Hovered = DBColors.brand8
var onBgBasicEmphasis80Pressed = DBColors.brand7
var onBgBasicEmphasis70Default = DBColors.brand8
var onBgBasicEmphasis70Hovered = DBColors.brand7
var onBgBasicEmphasis70Pressed = DBColors.brand6
var onBgBasicEmphasis60Default = DBColors.brand6
var onBgBasicEmphasis60Hovered = DBColors.brand5
var onBgBasicEmphasis60Pressed = DBColors.brand4
var onBgBasicEmphasis50Default = DBColors.brand5
var onBgBasicEmphasis50Hovered = DBColors.brand4
var onBgBasicEmphasis50Pressed = DBColors.brand3
var bgInvertedContrastMaxDefault = DBColors.brand12
var bgInvertedContrastMaxHovered = DBColors.brand11
var bgInvertedContrastMaxPressed = DBColors.brand10
var bgInvertedContrastHighDefault = DBColors.brand9
var bgInvertedContrastHighHovered = DBColors.brand8
var bgInvertedContrastHighPressed = DBColors.brand7
var bgInvertedContrastLowDefault = DBColors.brand8
var bgInvertedContrastLowHovered = DBColors.brand7
var bgInvertedContrastLowPressed = DBColors.brand6
var onBgInvertedDefault = DBColors.brand3
var onBgInvertedHovered = DBColors.brand4
var onBgInvertedPressed = DBColors.brand5
var onOriginDefault = DBColors.brandOnOriginDefaultDark
var onOriginHovered = DBColors.brandOnOriginHoveredDark
var onOriginPressed = DBColors.brandOnOriginPressedDark
var originDefault = DBColors.brandOriginDefaultDark
var originHovered = DBColors.brandOriginHoveredDark
var originPressed = DBColors.brandOriginPressedDark
}
@Observable
class InformationalColorsDark: AdaptiveColors {
var bgBasicLevel1Default = DBColors.informational3
var bgBasicLevel1Hovered = DBColors.informational4
var bgBasicLevel1Pressed = DBColors.informational5
var bgBasicLevel2Default = DBColors.informational2
var bgBasicLevel2Hovered = DBColors.informational3
var bgBasicLevel2Pressed = DBColors.informational4
var bgBasicLevel3Default = DBColors.informational1
var bgBasicLevel3Hovered = DBColors.informational2
var bgBasicLevel3Pressed = DBColors.informational3
var bgBasicTransparentFullDefault = DBColors.informational9.opacity(1)
var bgBasicTransparentSemiDefault = DBColors.informational9.opacity(0.84)
var bgBasicTransparentHovered = DBColors.informational9.opacity(0.76)
var bgBasicTransparentPressed = DBColors.informational9.opacity(0.68)
var onBgBasicEmphasis100Default = DBColors.informational12
var onBgBasicEmphasis100Hovered = DBColors.informational11
var onBgBasicEmphasis100Pressed = DBColors.informational10
var onBgBasicEmphasis90Default = DBColors.informational10
var onBgBasicEmphasis90Hovered = DBColors.informational9
var onBgBasicEmphasis90Pressed = DBColors.informational8
var onBgBasicEmphasis80Default = DBColors.informational9
var onBgBasicEmphasis80Hovered = DBColors.informational8
var onBgBasicEmphasis80Pressed = DBColors.informational7
var onBgBasicEmphasis70Default = DBColors.informational8
var onBgBasicEmphasis70Hovered = DBColors.informational7
var onBgBasicEmphasis70Pressed = DBColors.informational6
var onBgBasicEmphasis60Default = DBColors.informational6
var onBgBasicEmphasis60Hovered = DBColors.informational5
var onBgBasicEmphasis60Pressed = DBColors.informational4
var onBgBasicEmphasis50Default = DBColors.informational5
var onBgBasicEmphasis50Hovered = DBColors.informational4
var onBgBasicEmphasis50Pressed = DBColors.informational3
var bgInvertedContrastMaxDefault = DBColors.informational12
var bgInvertedContrastMaxHovered = DBColors.informational11
var bgInvertedContrastMaxPressed = DBColors.informational10
var bgInvertedContrastHighDefault = DBColors.informational9
var bgInvertedContrastHighHovered = DBColors.informational8
var bgInvertedContrastHighPressed = DBColors.informational7
var bgInvertedContrastLowDefault = DBColors.informational8
var bgInvertedContrastLowHovered = DBColors.informational7
var bgInvertedContrastLowPressed = DBColors.informational6
var onBgInvertedDefault = DBColors.informational3
var onBgInvertedHovered = DBColors.informational4
var onBgInvertedPressed = DBColors.informational5
var onOriginDefault = DBColors.informationalOnOriginDefaultDark
var onOriginHovered = DBColors.informationalOnOriginHoveredDark
var onOriginPressed = DBColors.informationalOnOriginPressedDark
var originDefault = DBColors.informationalOriginDefaultDark
var originHovered = DBColors.informationalOriginHoveredDark
var originPressed = DBColors.informationalOriginPressedDark
}
@Observable
class WarningColorsDark: AdaptiveColors {
var bgBasicLevel1Default = DBColors.warning3
var bgBasicLevel1Hovered = DBColors.warning4
var bgBasicLevel1Pressed = DBColors.warning5
var bgBasicLevel2Default = DBColors.warning2
var bgBasicLevel2Hovered = DBColors.warning3
var bgBasicLevel2Pressed = DBColors.warning4
var bgBasicLevel3Default = DBColors.warning1
var bgBasicLevel3Hovered = DBColors.warning2
var bgBasicLevel3Pressed = DBColors.warning3
var bgBasicTransparentFullDefault = DBColors.warning9.opacity(1)
var bgBasicTransparentSemiDefault = DBColors.warning9.opacity(0.84)
var bgBasicTransparentHovered = DBColors.warning9.opacity(0.76)
var bgBasicTransparentPressed = DBColors.warning9.opacity(0.68)
var onBgBasicEmphasis100Default = DBColors.warning12
var onBgBasicEmphasis100Hovered = DBColors.warning11
var onBgBasicEmphasis100Pressed = DBColors.warning10
var onBgBasicEmphasis90Default = DBColors.warning10
var onBgBasicEmphasis90Hovered = DBColors.warning9
var onBgBasicEmphasis90Pressed = DBColors.warning8
var onBgBasicEmphasis80Default = DBColors.warning9
var onBgBasicEmphasis80Hovered = DBColors.warning8
var onBgBasicEmphasis80Pressed = DBColors.warning7
var onBgBasicEmphasis70Default = DBColors.warning8
var onBgBasicEmphasis70Hovered = DBColors.warning7
var onBgBasicEmphasis70Pressed = DBColors.warning6
var onBgBasicEmphasis60Default = DBColors.warning6
var onBgBasicEmphasis60Hovered = DBColors.warning5
var onBgBasicEmphasis60Pressed = DBColors.warning4
var onBgBasicEmphasis50Default = DBColors.warning5
var onBgBasicEmphasis50Hovered = DBColors.warning4
var onBgBasicEmphasis50Pressed = DBColors.warning3
var bgInvertedContrastMaxDefault = DBColors.warning12
var bgInvertedContrastMaxHovered = DBColors.warning11
var bgInvertedContrastMaxPressed = DBColors.warning10
var bgInvertedContrastHighDefault = DBColors.warning9
var bgInvertedContrastHighHovered = DBColors.warning8
var bgInvertedContrastHighPressed = DBColors.warning7
var bgInvertedContrastLowDefault = DBColors.warning8
var bgInvertedContrastLowHovered = DBColors.warning7
var bgInvertedContrastLowPressed = DBColors.warning6
var onBgInvertedDefault = DBColors.warning3
var onBgInvertedHovered = DBColors.warning4
var onBgInvertedPressed = DBColors.warning5
var onOriginDefault = DBColors.warningOnOriginDefaultDark
var onOriginHovered = DBColors.warningOnOriginHoveredDark
var onOriginPressed = DBColors.warningOnOriginPressedDark
var originDefault = DBColors.warningOriginDefaultDark
var originHovered = DBColors.warningOriginHoveredDark
var originPressed = DBColors.warningOriginPressedDark
}
@Observable
class SuccessfulColorsDark: AdaptiveColors {
var bgBasicLevel1Default = DBColors.successful3
var bgBasicLevel1Hovered = DBColors.successful4
var bgBasicLevel1Pressed = DBColors.successful5
var bgBasicLevel2Default = DBColors.successful2
var bgBasicLevel2Hovered = DBColors.successful3
var bgBasicLevel2Pressed = DBColors.successful4
var bgBasicLevel3Default = DBColors.successful1
var bgBasicLevel3Hovered = DBColors.successful2
var bgBasicLevel3Pressed = DBColors.successful3
var bgBasicTransparentFullDefault = DBColors.successful9.opacity(1)
var bgBasicTransparentSemiDefault = DBColors.successful9.opacity(0.84)
var bgBasicTransparentHovered = DBColors.successful9.opacity(0.76)
var bgBasicTransparentPressed = DBColors.successful9.opacity(0.68)
var onBgBasicEmphasis100Default = DBColors.successful12
var onBgBasicEmphasis100Hovered = DBColors.successful11
var onBgBasicEmphasis100Pressed = DBColors.successful10
var onBgBasicEmphasis90Default = DBColors.successful10
var onBgBasicEmphasis90Hovered = DBColors.successful9
var onBgBasicEmphasis90Pressed = DBColors.successful8
var onBgBasicEmphasis80Default = DBColors.successful9
var onBgBasicEmphasis80Hovered = DBColors.successful8
var onBgBasicEmphasis80Pressed = DBColors.successful7
var onBgBasicEmphasis70Default = DBColors.successful8
var onBgBasicEmphasis70Hovered = DBColors.successful7
var onBgBasicEmphasis70Pressed = DBColors.successful6
var onBgBasicEmphasis60Default = DBColors.successful6
var onBgBasicEmphasis60Hovered = DBColors.successful5
var onBgBasicEmphasis60Pressed = DBColors.successful4
var onBgBasicEmphasis50Default = DBColors.successful5
var onBgBasicEmphasis50Hovered = DBColors.successful4
var onBgBasicEmphasis50Pressed = DBColors.successful3
var bgInvertedContrastMaxDefault = DBColors.successful12
var bgInvertedContrastMaxHovered = DBColors.successful11
var bgInvertedContrastMaxPressed = DBColors.successful10
var bgInvertedContrastHighDefault = DBColors.successful9
var bgInvertedContrastHighHovered = DBColors.successful8
var bgInvertedContrastHighPressed = DBColors.successful7
var bgInvertedContrastLowDefault = DBColors.successful8
var bgInvertedContrastLowHovered = DBColors.successful7
var bgInvertedContrastLowPressed = DBColors.successful6
var onBgInvertedDefault = DBColors.successful3
var onBgInvertedHovered = DBColors.successful4
var onBgInvertedPressed = DBColors.successful5
var onOriginDefault = DBColors.successfulOnOriginDefaultDark
var onOriginHovered = DBColors.successfulOnOriginHoveredDark
var onOriginPressed = DBColors.successfulOnOriginPressedDark
var originDefault = DBColors.successfulOriginDefaultDark
var originHovered = DBColors.successfulOriginHoveredDark
var originPressed = DBColors.successfulOriginPressedDark
}
@Observable
class CriticalColorsDark: AdaptiveColors {
var bgBasicLevel1Default = DBColors.critical3
var bgBasicLevel1Hovered = DBColors.critical4
var bgBasicLevel1Pressed = DBColors.critical5
var bgBasicLevel2Default = DBColors.critical2
var bgBasicLevel2Hovered = DBColors.critical3
var bgBasicLevel2Pressed = DBColors.critical4
var bgBasicLevel3Default = DBColors.critical1
var bgBasicLevel3Hovered = DBColors.critical2
var bgBasicLevel3Pressed = DBColors.critical3
var bgBasicTransparentFullDefault = DBColors.critical9.opacity(1)
var bgBasicTransparentSemiDefault = DBColors.critical9.opacity(0.84)
var bgBasicTransparentHovered = DBColors.critical9.opacity(0.76)
var bgBasicTransparentPressed = DBColors.critical9.opacity(0.68)
var onBgBasicEmphasis100Default = DBColors.critical12
var onBgBasicEmphasis100Hovered = DBColors.critical11
var onBgBasicEmphasis100Pressed = DBColors.critical10
var onBgBasicEmphasis90Default = DBColors.critical10
var onBgBasicEmphasis90Hovered = DBColors.critical9
var onBgBasicEmphasis90Pressed = DBColors.critical8
var onBgBasicEmphasis80Default = DBColors.critical9
var onBgBasicEmphasis80Hovered = DBColors.critical8
var onBgBasicEmphasis80Pressed = DBColors.critical7
var onBgBasicEmphasis70Default = DBColors.critical8
var onBgBasicEmphasis70Hovered = DBColors.critical7
var onBgBasicEmphasis70Pressed = DBColors.critical6
var onBgBasicEmphasis60Default = DBColors.critical6
var onBgBasicEmphasis60Hovered = DBColors.critical5
var onBgBasicEmphasis60Pressed = DBColors.critical4
var onBgBasicEmphasis50Default = DBColors.critical5
var onBgBasicEmphasis50Hovered = DBColors.critical4
var onBgBasicEmphasis50Pressed = DBColors.critical3
var bgInvertedContrastMaxDefault = DBColors.critical12
var bgInvertedContrastMaxHovered = DBColors.critical11
var bgInvertedContrastMaxPressed = DBColors.critical10
var bgInvertedContrastHighDefault = DBColors.critical9
var bgInvertedContrastHighHovered = DBColors.critical8
var bgInvertedContrastHighPressed = DBColors.critical7
var bgInvertedContrastLowDefault = DBColors.critical8
var bgInvertedContrastLowHovered = DBColors.critical7
var bgInvertedContrastLowPressed = DBColors.critical6
var onBgInvertedDefault = DBColors.critical3
var onBgInvertedHovered = DBColors.critical4
var onBgInvertedPressed = DBColors.critical5
var onOriginDefault = DBColors.criticalOnOriginDefaultDark
var onOriginHovered = DBColors.criticalOnOriginHoveredDark
var onOriginPressed = DBColors.criticalOnOriginPressedDark
var originDefault = DBColors.criticalOriginDefaultDark
var originHovered = DBColors.criticalOriginHoveredDark
var originPressed = DBColors.criticalOriginPressedDark
}
@Observable
class YellowColorsDark: AdaptiveColors {
var bgBasicLevel1Default = DBColors.yellow3
var bgBasicLevel1Hovered = DBColors.yellow4
var bgBasicLevel1Pressed = DBColors.yellow5
var bgBasicLevel2Default = DBColors.yellow2
var bgBasicLevel2Hovered = DBColors.yellow3
var bgBasicLevel2Pressed = DBColors.yellow4
var bgBasicLevel3Default = DBColors.yellow1
var bgBasicLevel3Hovered = DBColors.yellow2
var bgBasicLevel3Pressed = DBColors.yellow3
var bgBasicTransparentFullDefault = DBColors.yellow9.opacity(1)
var bgBasicTransparentSemiDefault = DBColors.yellow9.opacity(0.84)
var bgBasicTransparentHovered = DBColors.yellow9.opacity(0.76)
var bgBasicTransparentPressed = DBColors.yellow9.opacity(0.68)
var onBgBasicEmphasis100Default = DBColors.yellow12
var onBgBasicEmphasis100Hovered = DBColors.yellow11
var onBgBasicEmphasis100Pressed = DBColors.yellow10
var onBgBasicEmphasis90Default = DBColors.yellow10
var onBgBasicEmphasis90Hovered = DBColors.yellow9
var onBgBasicEmphasis90Pressed = DBColors.yellow8
var onBgBasicEmphasis80Default = DBColors.yellow9
var onBgBasicEmphasis80Hovered = DBColors.yellow8
var onBgBasicEmphasis80Pressed = DBColors.yellow7
var onBgBasicEmphasis70Default = DBColors.yellow8
var onBgBasicEmphasis70Hovered = DBColors.yellow7
var onBgBasicEmphasis70Pressed = DBColors.yellow6
var onBgBasicEmphasis60Default = DBColors.yellow6
var onBgBasicEmphasis60Hovered = DBColors.yellow5
var onBgBasicEmphasis60Pressed = DBColors.yellow4
var onBgBasicEmphasis50Default = DBColors.yellow5
var onBgBasicEmphasis50Hovered = DBColors.yellow4
var onBgBasicEmphasis50Pressed = DBColors.yellow3
var bgInvertedContrastMaxDefault = DBColors.yellow12
var bgInvertedContrastMaxHovered = DBColors.yellow11
var bgInvertedContrastMaxPressed = DBColors.yellow10
var bgInvertedContrastHighDefault = DBColors.yellow9
var bgInvertedContrastHighHovered = DBColors.yellow8
var bgInvertedContrastHighPressed = DBColors.yellow7
var bgInvertedContrastLowDefault = DBColors.yellow8
var bgInvertedContrastLowHovered = DBColors.yellow7
var bgInvertedContrastLowPressed = DBColors.yellow6
var onBgInvertedDefault = DBColors.yellow3
var onBgInvertedHovered = DBColors.yellow4
var onBgInvertedPressed = DBColors.yellow5
var onOriginDefault = DBColors.yellowOnOriginDefaultDark
var onOriginHovered = DBColors.yellowOnOriginHoveredDark
var onOriginPressed = DBColors.yellowOnOriginPressedDark
var originDefault = DBColors.yellowOriginDefaultDark
var originHovered = DBColors.yellowOriginHoveredDark
var originPressed = DBColors.yellowOriginPressedDark
}
@Observable
class OrangeColorsDark: AdaptiveColors {
var bgBasicLevel1Default = DBColors.orange3
var bgBasicLevel1Hovered = DBColors.orange4
var bgBasicLevel1Pressed = DBColors.orange5
var bgBasicLevel2Default = DBColors.orange2
var bgBasicLevel2Hovered = DBColors.orange3
var bgBasicLevel2Pressed = DBColors.orange4
var bgBasicLevel3Default = DBColors.orange1
var bgBasicLevel3Hovered = DBColors.orange2
var bgBasicLevel3Pressed = DBColors.orange3
var bgBasicTransparentFullDefault = DBColors.orange9.opacity(1)
var bgBasicTransparentSemiDefault = DBColors.orange9.opacity(0.84)
var bgBasicTransparentHovered = DBColors.orange9.opacity(0.76)
var bgBasicTransparentPressed = DBColors.orange9.opacity(0.68)
var onBgBasicEmphasis100Default = DBColors.orange12
var onBgBasicEmphasis100Hovered = DBColors.orange11
var onBgBasicEmphasis100Pressed = DBColors.orange10
var onBgBasicEmphasis90Default = DBColors.orange10
var onBgBasicEmphasis90Hovered = DBColors.orange9
var onBgBasicEmphasis90Pressed = DBColors.orange8
var onBgBasicEmphasis80Default = DBColors.orange9
var onBgBasicEmphasis80Hovered = DBColors.orange8
var onBgBasicEmphasis80Pressed = DBColors.orange7
var onBgBasicEmphasis70Default = DBColors.orange8
var onBgBasicEmphasis70Hovered = DBColors.orange7
var onBgBasicEmphasis70Pressed = DBColors.orange6
var onBgBasicEmphasis60Default = DBColors.orange6
var onBgBasicEmphasis60Hovered = DBColors.orange5
var onBgBasicEmphasis60Pressed = DBColors.orange4
var onBgBasicEmphasis50Default = DBColors.orange5
var onBgBasicEmphasis50Hovered = DBColors.orange4
var onBgBasicEmphasis50Pressed = DBColors.orange3
var bgInvertedContrastMaxDefault = DBColors.orange12
var bgInvertedContrastMaxHovered = DBColors.orange11
var bgInvertedContrastMaxPressed = DBColors.orange10
var bgInvertedContrastHighDefault = DBColors.orange9
var bgInvertedContrastHighHovered = DBColors.orange8
var bgInvertedContrastHighPressed = DBColors.orange7
var bgInvertedContrastLowDefault = DBColors.orange8
var bgInvertedContrastLowHovered = DBColors.orange7
var bgInvertedContrastLowPressed = DBColors.orange6
var onBgInvertedDefault = DBColors.orange3
var onBgInvertedHovered = DBColors.orange4
var onBgInvertedPressed = DBColors.orange5
var onOriginDefault = DBColors.orangeOnOriginDefaultDark
var onOriginHovered = DBColors.orangeOnOriginHoveredDark
var onOriginPressed = DBColors.orangeOnOriginPressedDark
var originDefault = DBColors.orangeOriginDefaultDark
var originHovered = DBColors.orangeOriginHoveredDark
var originPressed = DBColors.orangeOriginPressedDark
}
@Observable
class RedColorsDark: AdaptiveColors {
var bgBasicLevel1Default = DBColors.red3
var bgBasicLevel1Hovered = DBColors.red4
var bgBasicLevel1Pressed = DBColors.red5
var bgBasicLevel2Default = DBColors.red2
var bgBasicLevel2Hovered = DBColors.red3
var bgBasicLevel2Pressed = DBColors.red4
var bgBasicLevel3Default = DBColors.red1
var bgBasicLevel3Hovered = DBColors.red2
var bgBasicLevel3Pressed = DBColors.red3
var bgBasicTransparentFullDefault = DBColors.red9.opacity(1)
var bgBasicTransparentSemiDefault = DBColors.red9.opacity(0.84)
var bgBasicTransparentHovered = DBColors.red9.opacity(0.76)
var bgBasicTransparentPressed = DBColors.red9.opacity(0.68)
var onBgBasicEmphasis100Default = DBColors.red12
var onBgBasicEmphasis100Hovered = DBColors.red11
var onBgBasicEmphasis100Pressed = DBColors.red10
var onBgBasicEmphasis90Default = DBColors.red10
var onBgBasicEmphasis90Hovered = DBColors.red9
var onBgBasicEmphasis90Pressed = DBColors.red8
var onBgBasicEmphasis80Default = DBColors.red9
var onBgBasicEmphasis80Hovered = DBColors.red8
var onBgBasicEmphasis80Pressed = DBColors.red7
var onBgBasicEmphasis70Default = DBColors.red8
var onBgBasicEmphasis70Hovered = DBColors.red7
var onBgBasicEmphasis70Pressed = DBColors.red6
var onBgBasicEmphasis60Default = DBColors.red6
var onBgBasicEmphasis60Hovered = DBColors.red5
var onBgBasicEmphasis60Pressed = DBColors.red4
var onBgBasicEmphasis50Default = DBColors.red5
var onBgBasicEmphasis50Hovered = DBColors.red4
var onBgBasicEmphasis50Pressed = DBColors.red3
var bgInvertedContrastMaxDefault = DBColors.red12
var bgInvertedContrastMaxHovered = DBColors.red11
var bgInvertedContrastMaxPressed = DBColors.red10
var bgInvertedContrastHighDefault = DBColors.red9
var bgInvertedContrastHighHovered = DBColors.red8
var bgInvertedContrastHighPressed = DBColors.red7
var bgInvertedContrastLowDefault = DBColors.red8
var bgInvertedContrastLowHovered = DBColors.red7
var bgInvertedContrastLowPressed = DBColors.red6
var onBgInvertedDefault = DBColors.red3
var onBgInvertedHovered = DBColors.red4
var onBgInvertedPressed = DBColors.red5
var onOriginDefault = DBColors.redOnOriginDefaultDark
var onOriginHovered = DBColors.redOnOriginHoveredDark
var onOriginPressed = DBColors.redOnOriginPressedDark
var originDefault = DBColors.redOriginDefaultDark
var originHovered = DBColors.redOriginHoveredDark
var originPressed = DBColors.redOriginPressedDark
}
@Observable
class PinkColorsDark: AdaptiveColors {
var bgBasicLevel1Default = DBColors.pink3
var bgBasicLevel1Hovered = DBColors.pink4
var bgBasicLevel1Pressed = DBColors.pink5
var bgBasicLevel2Default = DBColors.pink2
var bgBasicLevel2Hovered = DBColors.pink3
var bgBasicLevel2Pressed = DBColors.pink4
var bgBasicLevel3Default = DBColors.pink1
var bgBasicLevel3Hovered = DBColors.pink2
var bgBasicLevel3Pressed = DBColors.pink3
var bgBasicTransparentFullDefault = DBColors.pink9.opacity(1)
var bgBasicTransparentSemiDefault = DBColors.pink9.opacity(0.84)
var bgBasicTransparentHovered = DBColors.pink9.opacity(0.76)
var bgBasicTransparentPressed = DBColors.pink9.opacity(0.68)
var onBgBasicEmphasis100Default = DBColors.pink12
var onBgBasicEmphasis100Hovered = DBColors.pink11
var onBgBasicEmphasis100Pressed = DBColors.pink10
var onBgBasicEmphasis90Default = DBColors.pink10
var onBgBasicEmphasis90Hovered = DBColors.pink9
var onBgBasicEmphasis90Pressed = DBColors.pink8
var onBgBasicEmphasis80Default = DBColors.pink9
var onBgBasicEmphasis80Hovered = DBColors.pink8
var onBgBasicEmphasis80Pressed = DBColors.pink7
var onBgBasicEmphasis70Default = DBColors.pink8
var onBgBasicEmphasis70Hovered = DBColors.pink7
var onBgBasicEmphasis70Pressed = DBColors.pink6
var onBgBasicEmphasis60Default = DBColors.pink6
var onBgBasicEmphasis60Hovered = DBColors.pink5
var onBgBasicEmphasis60Pressed = DBColors.pink4
var onBgBasicEmphasis50Default = DBColors.pink5
var onBgBasicEmphasis50Hovered = DBColors.pink4
var onBgBasicEmphasis50Pressed = DBColors.pink3
var bgInvertedContrastMaxDefault = DBColors.pink12
var bgInvertedContrastMaxHovered = DBColors.pink11
var bgInvertedContrastMaxPressed = DBColors.pink10
var bgInvertedContrastHighDefault = DBColors.pink9
var bgInvertedContrastHighHovered = DBColors.pink8
var bgInvertedContrastHighPressed = DBColors.pink7
var bgInvertedContrastLowDefault = DBColors.pink8
var bgInvertedContrastLowHovered = DBColors.pink7
var bgInvertedContrastLowPressed = DBColors.pink6
var onBgInvertedDefault = DBColors.pink3
var onBgInvertedHovered = DBColors.pink4
var onBgInvertedPressed = DBColors.pink5
var onOriginDefault = DBColors.pinkOnOriginDefaultDark
var onOriginHovered = DBColors.pinkOnOriginHoveredDark
var onOriginPressed = DBColors.pinkOnOriginPressedDark
var originDefault = DBColors.pinkOriginDefaultDark
var originHovered = DBColors.pinkOriginHoveredDark
var originPressed = DBColors.pinkOriginPressedDark
}
@Observable
class VioletColorsDark: AdaptiveColors {
var bgBasicLevel1Default = DBColors.violet3
var bgBasicLevel1Hovered = DBColors.violet4
var bgBasicLevel1Pressed = DBColors.violet5
var bgBasicLevel2Default = DBColors.violet2
var bgBasicLevel2Hovered = DBColors.violet3
var bgBasicLevel2Pressed = DBColors.violet4
var bgBasicLevel3Default = DBColors.violet1
var bgBasicLevel3Hovered = DBColors.violet2
var bgBasicLevel3Pressed = DBColors.violet3
var bgBasicTransparentFullDefault = DBColors.violet9.opacity(1)
var bgBasicTransparentSemiDefault = DBColors.violet9.opacity(0.84)
var bgBasicTransparentHovered = DBColors.violet9.opacity(0.76)
var bgBasicTransparentPressed = DBColors.violet9.opacity(0.68)
var onBgBasicEmphasis100Default = DBColors.violet12
var onBgBasicEmphasis100Hovered = DBColors.violet11
var onBgBasicEmphasis100Pressed = DBColors.violet10
var onBgBasicEmphasis90Default = DBColors.violet10
var onBgBasicEmphasis90Hovered = DBColors.violet9
var onBgBasicEmphasis90Pressed = DBColors.violet8
var onBgBasicEmphasis80Default = DBColors.violet9
var onBgBasicEmphasis80Hovered = DBColors.violet8
var onBgBasicEmphasis80Pressed = DBColors.violet7
var onBgBasicEmphasis70Default = DBColors.violet8
var onBgBasicEmphasis70Hovered = DBColors.violet7
var onBgBasicEmphasis70Pressed = DBColors.violet6
var onBgBasicEmphasis60Default = DBColors.violet6
var onBgBasicEmphasis60Hovered = DBColors.violet5
var onBgBasicEmphasis60Pressed = DBColors.violet4
var onBgBasicEmphasis50Default = DBColors.violet5
var onBgBasicEmphasis50Hovered = DBColors.violet4
var onBgBasicEmphasis50Pressed = DBColors.violet3
var bgInvertedContrastMaxDefault = DBColors.violet12
var bgInvertedContrastMaxHovered = DBColors.violet11
var bgInvertedContrastMaxPressed = DBColors.violet10
var bgInvertedContrastHighDefault = DBColors.violet9
var bgInvertedContrastHighHovered = DBColors.violet8
var bgInvertedContrastHighPressed = DBColors.violet7
var bgInvertedContrastLowDefault = DBColors.violet8
var bgInvertedContrastLowHovered = DBColors.violet7
var bgInvertedContrastLowPressed = DBColors.violet6
var onBgInvertedDefault = DBColors.violet3
var onBgInvertedHovered = DBColors.violet4
var onBgInvertedPressed = DBColors.violet5
var onOriginDefault = DBColors.violetOnOriginDefaultDark
var onOriginHovered = DBColors.violetOnOriginHoveredDark
var onOriginPressed = DBColors.violetOnOriginPressedDark
var originDefault = DBColors.violetOriginDefaultDark
var originHovered = DBColors.violetOriginHoveredDark
var originPressed = DBColors.violetOriginPressedDark
}
@Observable
class BlueColorsDark: AdaptiveColors {
var bgBasicLevel1Default = DBColors.blue3
var bgBasicLevel1Hovered = DBColors.blue4
var bgBasicLevel1Pressed = DBColors.blue5
var bgBasicLevel2Default = DBColors.blue2
var bgBasicLevel2Hovered = DBColors.blue3
var bgBasicLevel2Pressed = DBColors.blue4
var bgBasicLevel3Default = DBColors.blue1
var bgBasicLevel3Hovered = DBColors.blue2
var bgBasicLevel3Pressed = DBColors.blue3
var bgBasicTransparentFullDefault = DBColors.blue9.opacity(1)
var bgBasicTransparentSemiDefault = DBColors.blue9.opacity(0.84)
var bgBasicTransparentHovered = DBColors.blue9.opacity(0.76)
var bgBasicTransparentPressed = DBColors.blue9.opacity(0.68)
var onBgBasicEmphasis100Default = DBColors.blue12
var onBgBasicEmphasis100Hovered = DBColors.blue11
var onBgBasicEmphasis100Pressed = DBColors.blue10
var onBgBasicEmphasis90Default = DBColors.blue10
var onBgBasicEmphasis90Hovered = DBColors.blue9
var onBgBasicEmphasis90Pressed = DBColors.blue8
var onBgBasicEmphasis80Default = DBColors.blue9
var onBgBasicEmphasis80Hovered = DBColors.blue8
var onBgBasicEmphasis80Pressed = DBColors.blue7
var onBgBasicEmphasis70Default = DBColors.blue8
var onBgBasicEmphasis70Hovered = DBColors.blue7
var onBgBasicEmphasis70Pressed = DBColors.blue6
var onBgBasicEmphasis60Default = DBColors.blue6
var onBgBasicEmphasis60Hovered = DBColors.blue5
var onBgBasicEmphasis60Pressed = DBColors.blue4
var onBgBasicEmphasis50Default = DBColors.blue5
var onBgBasicEmphasis50Hovered = DBColors.blue4
var onBgBasicEmphasis50Pressed = DBColors.blue3
var bgInvertedContrastMaxDefault = DBColors.blue12
var bgInvertedContrastMaxHovered = DBColors.blue11
var bgInvertedContrastMaxPressed = DBColors.blue10
var bgInvertedContrastHighDefault = DBColors.blue9
var bgInvertedContrastHighHovered = DBColors.blue8
var bgInvertedContrastHighPressed = DBColors.blue7
var bgInvertedContrastLowDefault = DBColors.blue8
var bgInvertedContrastLowHovered = DBColors.blue7
var bgInvertedContrastLowPressed = DBColors.blue6
var onBgInvertedDefault = DBColors.blue3
var onBgInvertedHovered = DBColors.blue4
var onBgInvertedPressed = DBColors.blue5
var onOriginDefault = DBColors.blueOnOriginDefaultDark
var onOriginHovered = DBColors.blueOnOriginHoveredDark
var onOriginPressed = DBColors.blueOnOriginPressedDark
var originDefault = DBColors.blueOriginDefaultDark
var originHovered = DBColors.blueOriginHoveredDark
var originPressed = DBColors.blueOriginPressedDark
}
@Observable
class CyanColorsDark: AdaptiveColors {
var bgBasicLevel1Default = DBColors.cyan3
var bgBasicLevel1Hovered = DBColors.cyan4
var bgBasicLevel1Pressed = DBColors.cyan5
var bgBasicLevel2Default = DBColors.cyan2
var bgBasicLevel2Hovered = DBColors.cyan3
var bgBasicLevel2Pressed = DBColors.cyan4
var bgBasicLevel3Default = DBColors.cyan1
var bgBasicLevel3Hovered = DBColors.cyan2
var bgBasicLevel3Pressed = DBColors.cyan3
var bgBasicTransparentFullDefault = DBColors.cyan9.opacity(1)
var bgBasicTransparentSemiDefault = DBColors.cyan9.opacity(0.84)
var bgBasicTransparentHovered = DBColors.cyan9.opacity(0.76)
var bgBasicTransparentPressed = DBColors.cyan9.opacity(0.68)
var onBgBasicEmphasis100Default = DBColors.cyan12
var onBgBasicEmphasis100Hovered = DBColors.cyan11
var onBgBasicEmphasis100Pressed = DBColors.cyan10
var onBgBasicEmphasis90Default = DBColors.cyan10
var onBgBasicEmphasis90Hovered = DBColors.cyan9
var onBgBasicEmphasis90Pressed = DBColors.cyan8
var onBgBasicEmphasis80Default = DBColors.cyan9
var onBgBasicEmphasis80Hovered = DBColors.cyan8
var onBgBasicEmphasis80Pressed = DBColors.cyan7
var onBgBasicEmphasis70Default = DBColors.cyan8
var onBgBasicEmphasis70Hovered = DBColors.cyan7
var onBgBasicEmphasis70Pressed = DBColors.cyan6
var onBgBasicEmphasis60Default = DBColors.cyan6
var onBgBasicEmphasis60Hovered = DBColors.cyan5
var onBgBasicEmphasis60Pressed = DBColors.cyan4
var onBgBasicEmphasis50Default = DBColors.cyan5
var onBgBasicEmphasis50Hovered = DBColors.cyan4
var onBgBasicEmphasis50Pressed = DBColors.cyan3
var bgInvertedContrastMaxDefault = DBColors.cyan12
var bgInvertedContrastMaxHovered = DBColors.cyan11
var bgInvertedContrastMaxPressed = DBColors.cyan10
var bgInvertedContrastHighDefault = DBColors.cyan9
var bgInvertedContrastHighHovered = DBColors.cyan8
var bgInvertedContrastHighPressed = DBColors.cyan7
var bgInvertedContrastLowDefault = DBColors.cyan8
var bgInvertedContrastLowHovered = DBColors.cyan7
var bgInvertedContrastLowPressed = DBColors.cyan6
var onBgInvertedDefault = DBColors.cyan3
var onBgInvertedHovered = DBColors.cyan4
var onBgInvertedPressed = DBColors.cyan5
var onOriginDefault = DBColors.cyanOnOriginDefaultDark
var onOriginHovered = DBColors.cyanOnOriginHoveredDark
var onOriginPressed = DBColors.cyanOnOriginPressedDark
var originDefault = DBColors.cyanOriginDefaultDark
var originHovered = DBColors.cyanOriginHoveredDark
var originPressed = DBColors.cyanOriginPressedDark
}
@Observable
class TurquoiseColorsDark: AdaptiveColors {
var bgBasicLevel1Default = DBColors.turquoise3
var bgBasicLevel1Hovered = DBColors.turquoise4
var bgBasicLevel1Pressed = DBColors.turquoise5
var bgBasicLevel2Default = DBColors.turquoise2
var bgBasicLevel2Hovered = DBColors.turquoise3
var bgBasicLevel2Pressed = DBColors.turquoise4
var bgBasicLevel3Default = DBColors.turquoise1
var bgBasicLevel3Hovered = DBColors.turquoise2
var bgBasicLevel3Pressed = DBColors.turquoise3
var bgBasicTransparentFullDefault = DBColors.turquoise9.opacity(1)
var bgBasicTransparentSemiDefault = DBColors.turquoise9.opacity(0.84)
var bgBasicTransparentHovered = DBColors.turquoise9.opacity(0.76)
var bgBasicTransparentPressed = DBColors.turquoise9.opacity(0.68)
var onBgBasicEmphasis100Default = DBColors.turquoise12
var onBgBasicEmphasis100Hovered = DBColors.turquoise11
var onBgBasicEmphasis100Pressed = DBColors.turquoise10
var onBgBasicEmphasis90Default = DBColors.turquoise10
var onBgBasicEmphasis90Hovered = DBColors.turquoise9
var onBgBasicEmphasis90Pressed = DBColors.turquoise8
var onBgBasicEmphasis80Default = DBColors.turquoise9
var onBgBasicEmphasis80Hovered = DBColors.turquoise8
var onBgBasicEmphasis80Pressed = DBColors.turquoise7
var onBgBasicEmphasis70Default = DBColors.turquoise8
var onBgBasicEmphasis70Hovered = DBColors.turquoise7
var onBgBasicEmphasis70Pressed = DBColors.turquoise6
var onBgBasicEmphasis60Default = DBColors.turquoise6
var onBgBasicEmphasis60Hovered = DBColors.turquoise5
var onBgBasicEmphasis60Pressed = DBColors.turquoise4
var onBgBasicEmphasis50Default = DBColors.turquoise5
var onBgBasicEmphasis50Hovered = DBColors.turquoise4
var onBgBasicEmphasis50Pressed = DBColors.turquoise3
var bgInvertedContrastMaxDefault = DBColors.turquoise12
var bgInvertedContrastMaxHovered = DBColors.turquoise11
var bgInvertedContrastMaxPressed = DBColors.turquoise10
var bgInvertedContrastHighDefault = DBColors.turquoise9
var bgInvertedContrastHighHovered = DBColors.turquoise8
var bgInvertedContrastHighPressed = DBColors.turquoise7
var bgInvertedContrastLowDefault = DBColors.turquoise8
var bgInvertedContrastLowHovered = DBColors.turquoise7
var bgInvertedContrastLowPressed = DBColors.turquoise6
var onBgInvertedDefault = DBColors.turquoise3
var onBgInvertedHovered = DBColors.turquoise4
var onBgInvertedPressed = DBColors.turquoise5
var onOriginDefault = DBColors.turquoiseOnOriginDefaultDark
var onOriginHovered = DBColors.turquoiseOnOriginHoveredDark
var onOriginPressed = DBColors.turquoiseOnOriginPressedDark
var originDefault = DBColors.turquoiseOriginDefaultDark
var originHovered = DBColors.turquoiseOriginHoveredDark
var originPressed = DBColors.turquoiseOriginPressedDark
}
@Observable
class GreenColorsDark: AdaptiveColors {
var bgBasicLevel1Default = DBColors.green3
var bgBasicLevel1Hovered = DBColors.green4
var bgBasicLevel1Pressed = DBColors.green5
var bgBasicLevel2Default = DBColors.green2
var bgBasicLevel2Hovered = DBColors.green3
var bgBasicLevel2Pressed = DBColors.green4
var bgBasicLevel3Default = DBColors.green1
var bgBasicLevel3Hovered = DBColors.green2
var bgBasicLevel3Pressed = DBColors.green3
var bgBasicTransparentFullDefault = DBColors.green9.opacity(1)
var bgBasicTransparentSemiDefault = DBColors.green9.opacity(0.84)
var bgBasicTransparentHovered = DBColors.green9.opacity(0.76)
var bgBasicTransparentPressed = DBColors.green9.opacity(0.68)
var onBgBasicEmphasis100Default = DBColors.green12
var onBgBasicEmphasis100Hovered = DBColors.green11
var onBgBasicEmphasis100Pressed = DBColors.green10
var onBgBasicEmphasis90Default = DBColors.green10
var onBgBasicEmphasis90Hovered = DBColors.green9
var onBgBasicEmphasis90Pressed = DBColors.green8
var onBgBasicEmphasis80Default = DBColors.green9
var onBgBasicEmphasis80Hovered = DBColors.green8
var onBgBasicEmphasis80Pressed = DBColors.green7
var onBgBasicEmphasis70Default = DBColors.green8
var onBgBasicEmphasis70Hovered = DBColors.green7
var onBgBasicEmphasis70Pressed = DBColors.green6
var onBgBasicEmphasis60Default = DBColors.green6
var onBgBasicEmphasis60Hovered = DBColors.green5
var onBgBasicEmphasis60Pressed = DBColors.green4
var onBgBasicEmphasis50Default = DBColors.green5
var onBgBasicEmphasis50Hovered = DBColors.green4
var onBgBasicEmphasis50Pressed = DBColors.green3
var bgInvertedContrastMaxDefault = DBColors.green12
var bgInvertedContrastMaxHovered = DBColors.green11
var bgInvertedContrastMaxPressed = DBColors.green10
var bgInvertedContrastHighDefault = DBColors.green9
var bgInvertedContrastHighHovered = DBColors.green8
var bgInvertedContrastHighPressed = DBColors.green7
var bgInvertedContrastLowDefault = DBColors.green8
var bgInvertedContrastLowHovered = DBColors.green7
var bgInvertedContrastLowPressed = DBColors.green6
var onBgInvertedDefault = DBColors.green3
var onBgInvertedHovered = DBColors.green4
var onBgInvertedPressed = DBColors.green5
var onOriginDefault = DBColors.greenOnOriginDefaultDark
var onOriginHovered = DBColors.greenOnOriginHoveredDark
var onOriginPressed = DBColors.greenOnOriginPressedDark
var originDefault = DBColors.greenOriginDefaultDark
var originHovered = DBColors.greenOriginHoveredDark
var originPressed = DBColors.greenOriginPressedDark
}
func getColorSchemeDark(
neutral: AdaptiveColors = NeutralColorsDark(),
brand: AdaptiveColors = BrandColorsDark(),
informational: AdaptiveColors = InformationalColorsDark(),
warning: AdaptiveColors = WarningColorsDark(),
successful: AdaptiveColors = SuccessfulColorsDark(),
critical: AdaptiveColors = CriticalColorsDark(),
yellow: AdaptiveColors = YellowColorsDark(),
orange: AdaptiveColors = OrangeColorsDark(),
red: AdaptiveColors = RedColorsDark(),
pink: AdaptiveColors = PinkColorsDark(),
violet: AdaptiveColors = VioletColorsDark(),
blue: AdaptiveColors = BlueColorsDark(),
cyan: AdaptiveColors = CyanColorsDark(),
turquoise: AdaptiveColors = TurquoiseColorsDark(),
green: AdaptiveColors = GreenColorsDark()
) -> DeutscheBahnThemeColorScheme { 
   DeutscheBahnThemeColorScheme(
neutral: neutral,
brand: brand,
informational: informational,
warning: warning,
successful: successful,
critical: critical,
yellow: yellow,
orange: orange,
red: red,
pink: pink,
violet: violet,
blue: blue,
cyan: cyan,
turquoise: turquoise,
green: green)
}
@Observable
class NeutralColorsLight: AdaptiveColors {
var bgBasicLevel1Default = DBColors.neutral14
var bgBasicLevel1Hovered = DBColors.neutral13
var bgBasicLevel1Pressed = DBColors.neutral12
var bgBasicLevel2Default = DBColors.neutral13
var bgBasicLevel2Hovered = DBColors.neutral12
var bgBasicLevel2Pressed = DBColors.neutral11
var bgBasicLevel3Default = DBColors.neutral12
var bgBasicLevel3Hovered = DBColors.neutral11
var bgBasicLevel3Pressed = DBColors.neutral10
var bgBasicTransparentFullDefault = DBColors.neutral6.opacity(1)
var bgBasicTransparentSemiDefault = DBColors.neutral6.opacity(0.84)
var bgBasicTransparentHovered = DBColors.neutral6.opacity(0.76)
var bgBasicTransparentPressed = DBColors.neutral6.opacity(0.68)
var onBgBasicEmphasis100Default = DBColors.neutral3
var onBgBasicEmphasis100Hovered = DBColors.neutral4
var onBgBasicEmphasis100Pressed = DBColors.neutral5
var onBgBasicEmphasis90Default = DBColors.neutral5
var onBgBasicEmphasis90Hovered = DBColors.neutral6
var onBgBasicEmphasis90Pressed = DBColors.neutral7
var onBgBasicEmphasis80Default = DBColors.neutral6
var onBgBasicEmphasis80Hovered = DBColors.neutral5
var onBgBasicEmphasis80Pressed = DBColors.neutral4
var onBgBasicEmphasis70Default = DBColors.neutral7
var onBgBasicEmphasis70Hovered = DBColors.neutral6
var onBgBasicEmphasis70Pressed = DBColors.neutral5
var onBgBasicEmphasis60Default = DBColors.neutral10
var onBgBasicEmphasis60Hovered = DBColors.neutral9
var onBgBasicEmphasis60Pressed = DBColors.neutral8
var onBgBasicEmphasis50Default = DBColors.neutral9
var onBgBasicEmphasis50Hovered = DBColors.neutral8
var onBgBasicEmphasis50Pressed = DBColors.neutral7
var bgInvertedContrastMaxDefault = DBColors.neutral3
var bgInvertedContrastMaxHovered = DBColors.neutral4
var bgInvertedContrastMaxPressed = DBColors.neutral5
var bgInvertedContrastHighDefault = DBColors.neutral6
var bgInvertedContrastHighHovered = DBColors.neutral5
var bgInvertedContrastHighPressed = DBColors.neutral4
var bgInvertedContrastLowDefault = DBColors.neutral7
var bgInvertedContrastLowHovered = DBColors.neutral6
var bgInvertedContrastLowPressed = DBColors.neutral5
var onBgInvertedDefault = DBColors.neutral14
var onBgInvertedHovered = DBColors.neutral13
var onBgInvertedPressed = DBColors.neutral12
var onOriginDefault = DBColors.neutralOnOriginDefaultLight
var onOriginHovered = DBColors.neutralOnOriginHoveredLight
var onOriginPressed = DBColors.neutralOnOriginPressedLight
var originDefault = DBColors.neutralOriginDefaultLight
var originHovered = DBColors.neutralOriginHoveredLight
var originPressed = DBColors.neutralOriginPressedLight
}
@Observable
class BrandColorsLight: AdaptiveColors {
var bgBasicLevel1Default = DBColors.brand14
var bgBasicLevel1Hovered = DBColors.brand13
var bgBasicLevel1Pressed = DBColors.brand12
var bgBasicLevel2Default = DBColors.brand13
var bgBasicLevel2Hovered = DBColors.brand12
var bgBasicLevel2Pressed = DBColors.brand11
var bgBasicLevel3Default = DBColors.brand12
var bgBasicLevel3Hovered = DBColors.brand11
var bgBasicLevel3Pressed = DBColors.brand10
var bgBasicTransparentFullDefault = DBColors.brand6.opacity(1)
var bgBasicTransparentSemiDefault = DBColors.brand6.opacity(0.84)
var bgBasicTransparentHovered = DBColors.brand6.opacity(0.76)
var bgBasicTransparentPressed = DBColors.brand6.opacity(0.68)
var onBgBasicEmphasis100Default = DBColors.brand3
var onBgBasicEmphasis100Hovered = DBColors.brand4
var onBgBasicEmphasis100Pressed = DBColors.brand5
var onBgBasicEmphasis90Default = DBColors.brand5
var onBgBasicEmphasis90Hovered = DBColors.brand6
var onBgBasicEmphasis90Pressed = DBColors.brand7
var onBgBasicEmphasis80Default = DBColors.brand6
var onBgBasicEmphasis80Hovered = DBColors.brand5
var onBgBasicEmphasis80Pressed = DBColors.brand4
var onBgBasicEmphasis70Default = DBColors.brand7
var onBgBasicEmphasis70Hovered = DBColors.brand6
var onBgBasicEmphasis70Pressed = DBColors.brand5
var onBgBasicEmphasis60Default = DBColors.brand10
var onBgBasicEmphasis60Hovered = DBColors.brand9
var onBgBasicEmphasis60Pressed = DBColors.brand8
var onBgBasicEmphasis50Default = DBColors.brand9
var onBgBasicEmphasis50Hovered = DBColors.brand8
var onBgBasicEmphasis50Pressed = DBColors.brand7
var bgInvertedContrastMaxDefault = DBColors.brand3
var bgInvertedContrastMaxHovered = DBColors.brand4
var bgInvertedContrastMaxPressed = DBColors.brand5
var bgInvertedContrastHighDefault = DBColors.brand6
var bgInvertedContrastHighHovered = DBColors.brand5
var bgInvertedContrastHighPressed = DBColors.brand4
var bgInvertedContrastLowDefault = DBColors.brand7
var bgInvertedContrastLowHovered = DBColors.brand6
var bgInvertedContrastLowPressed = DBColors.brand5
var onBgInvertedDefault = DBColors.brand14
var onBgInvertedHovered = DBColors.brand13
var onBgInvertedPressed = DBColors.brand12
var onOriginDefault = DBColors.brandOnOriginDefaultLight
var onOriginHovered = DBColors.brandOnOriginHoveredLight
var onOriginPressed = DBColors.brandOnOriginPressedLight
var originDefault = DBColors.brandOriginDefaultLight
var originHovered = DBColors.brandOriginHoveredLight
var originPressed = DBColors.brandOriginPressedLight
}
@Observable
class InformationalColorsLight: AdaptiveColors {
var bgBasicLevel1Default = DBColors.informational14
var bgBasicLevel1Hovered = DBColors.informational13
var bgBasicLevel1Pressed = DBColors.informational12
var bgBasicLevel2Default = DBColors.informational13
var bgBasicLevel2Hovered = DBColors.informational12
var bgBasicLevel2Pressed = DBColors.informational11
var bgBasicLevel3Default = DBColors.informational12
var bgBasicLevel3Hovered = DBColors.informational11
var bgBasicLevel3Pressed = DBColors.informational10
var bgBasicTransparentFullDefault = DBColors.informational6.opacity(1)
var bgBasicTransparentSemiDefault = DBColors.informational6.opacity(0.84)
var bgBasicTransparentHovered = DBColors.informational6.opacity(0.76)
var bgBasicTransparentPressed = DBColors.informational6.opacity(0.68)
var onBgBasicEmphasis100Default = DBColors.informational3
var onBgBasicEmphasis100Hovered = DBColors.informational4
var onBgBasicEmphasis100Pressed = DBColors.informational5
var onBgBasicEmphasis90Default = DBColors.informational5
var onBgBasicEmphasis90Hovered = DBColors.informational6
var onBgBasicEmphasis90Pressed = DBColors.informational7
var onBgBasicEmphasis80Default = DBColors.informational6
var onBgBasicEmphasis80Hovered = DBColors.informational5
var onBgBasicEmphasis80Pressed = DBColors.informational4
var onBgBasicEmphasis70Default = DBColors.informational7
var onBgBasicEmphasis70Hovered = DBColors.informational6
var onBgBasicEmphasis70Pressed = DBColors.informational5
var onBgBasicEmphasis60Default = DBColors.informational10
var onBgBasicEmphasis60Hovered = DBColors.informational9
var onBgBasicEmphasis60Pressed = DBColors.informational8
var onBgBasicEmphasis50Default = DBColors.informational9
var onBgBasicEmphasis50Hovered = DBColors.informational8
var onBgBasicEmphasis50Pressed = DBColors.informational7
var bgInvertedContrastMaxDefault = DBColors.informational3
var bgInvertedContrastMaxHovered = DBColors.informational4
var bgInvertedContrastMaxPressed = DBColors.informational5
var bgInvertedContrastHighDefault = DBColors.informational6
var bgInvertedContrastHighHovered = DBColors.informational5
var bgInvertedContrastHighPressed = DBColors.informational4
var bgInvertedContrastLowDefault = DBColors.informational7
var bgInvertedContrastLowHovered = DBColors.informational6
var bgInvertedContrastLowPressed = DBColors.informational5
var onBgInvertedDefault = DBColors.informational14
var onBgInvertedHovered = DBColors.informational13
var onBgInvertedPressed = DBColors.informational12
var onOriginDefault = DBColors.informationalOnOriginDefaultLight
var onOriginHovered = DBColors.informationalOnOriginHoveredLight
var onOriginPressed = DBColors.informationalOnOriginPressedLight
var originDefault = DBColors.informationalOriginDefaultLight
var originHovered = DBColors.informationalOriginHoveredLight
var originPressed = DBColors.informationalOriginPressedLight
}
@Observable
class WarningColorsLight: AdaptiveColors {
var bgBasicLevel1Default = DBColors.warning14
var bgBasicLevel1Hovered = DBColors.warning13
var bgBasicLevel1Pressed = DBColors.warning12
var bgBasicLevel2Default = DBColors.warning13
var bgBasicLevel2Hovered = DBColors.warning12
var bgBasicLevel2Pressed = DBColors.warning11
var bgBasicLevel3Default = DBColors.warning12
var bgBasicLevel3Hovered = DBColors.warning11
var bgBasicLevel3Pressed = DBColors.warning10
var bgBasicTransparentFullDefault = DBColors.warning6.opacity(1)
var bgBasicTransparentSemiDefault = DBColors.warning6.opacity(0.84)
var bgBasicTransparentHovered = DBColors.warning6.opacity(0.76)
var bgBasicTransparentPressed = DBColors.warning6.opacity(0.68)
var onBgBasicEmphasis100Default = DBColors.warning3
var onBgBasicEmphasis100Hovered = DBColors.warning4
var onBgBasicEmphasis100Pressed = DBColors.warning5
var onBgBasicEmphasis90Default = DBColors.warning5
var onBgBasicEmphasis90Hovered = DBColors.warning6
var onBgBasicEmphasis90Pressed = DBColors.warning7
var onBgBasicEmphasis80Default = DBColors.warning6
var onBgBasicEmphasis80Hovered = DBColors.warning5
var onBgBasicEmphasis80Pressed = DBColors.warning4
var onBgBasicEmphasis70Default = DBColors.warning7
var onBgBasicEmphasis70Hovered = DBColors.warning6
var onBgBasicEmphasis70Pressed = DBColors.warning5
var onBgBasicEmphasis60Default = DBColors.warning10
var onBgBasicEmphasis60Hovered = DBColors.warning9
var onBgBasicEmphasis60Pressed = DBColors.warning8
var onBgBasicEmphasis50Default = DBColors.warning9
var onBgBasicEmphasis50Hovered = DBColors.warning8
var onBgBasicEmphasis50Pressed = DBColors.warning7
var bgInvertedContrastMaxDefault = DBColors.warning3
var bgInvertedContrastMaxHovered = DBColors.warning4
var bgInvertedContrastMaxPressed = DBColors.warning5
var bgInvertedContrastHighDefault = DBColors.warning6
var bgInvertedContrastHighHovered = DBColors.warning5
var bgInvertedContrastHighPressed = DBColors.warning4
var bgInvertedContrastLowDefault = DBColors.warning7
var bgInvertedContrastLowHovered = DBColors.warning6
var bgInvertedContrastLowPressed = DBColors.warning5
var onBgInvertedDefault = DBColors.warning14
var onBgInvertedHovered = DBColors.warning13
var onBgInvertedPressed = DBColors.warning12
var onOriginDefault = DBColors.warningOnOriginDefaultLight
var onOriginHovered = DBColors.warningOnOriginHoveredLight
var onOriginPressed = DBColors.warningOnOriginPressedLight
var originDefault = DBColors.warningOriginDefaultLight
var originHovered = DBColors.warningOriginHoveredLight
var originPressed = DBColors.warningOriginPressedLight
}
@Observable
class SuccessfulColorsLight: AdaptiveColors {
var bgBasicLevel1Default = DBColors.successful14
var bgBasicLevel1Hovered = DBColors.successful13
var bgBasicLevel1Pressed = DBColors.successful12
var bgBasicLevel2Default = DBColors.successful13
var bgBasicLevel2Hovered = DBColors.successful12
var bgBasicLevel2Pressed = DBColors.successful11
var bgBasicLevel3Default = DBColors.successful12
var bgBasicLevel3Hovered = DBColors.successful11
var bgBasicLevel3Pressed = DBColors.successful10
var bgBasicTransparentFullDefault = DBColors.successful6.opacity(1)
var bgBasicTransparentSemiDefault = DBColors.successful6.opacity(0.84)
var bgBasicTransparentHovered = DBColors.successful6.opacity(0.76)
var bgBasicTransparentPressed = DBColors.successful6.opacity(0.68)
var onBgBasicEmphasis100Default = DBColors.successful3
var onBgBasicEmphasis100Hovered = DBColors.successful4
var onBgBasicEmphasis100Pressed = DBColors.successful5
var onBgBasicEmphasis90Default = DBColors.successful5
var onBgBasicEmphasis90Hovered = DBColors.successful6
var onBgBasicEmphasis90Pressed = DBColors.successful7
var onBgBasicEmphasis80Default = DBColors.successful6
var onBgBasicEmphasis80Hovered = DBColors.successful5
var onBgBasicEmphasis80Pressed = DBColors.successful4
var onBgBasicEmphasis70Default = DBColors.successful7
var onBgBasicEmphasis70Hovered = DBColors.successful6
var onBgBasicEmphasis70Pressed = DBColors.successful5
var onBgBasicEmphasis60Default = DBColors.successful10
var onBgBasicEmphasis60Hovered = DBColors.successful9
var onBgBasicEmphasis60Pressed = DBColors.successful8
var onBgBasicEmphasis50Default = DBColors.successful9
var onBgBasicEmphasis50Hovered = DBColors.successful8
var onBgBasicEmphasis50Pressed = DBColors.successful7
var bgInvertedContrastMaxDefault = DBColors.successful3
var bgInvertedContrastMaxHovered = DBColors.successful4
var bgInvertedContrastMaxPressed = DBColors.successful5
var bgInvertedContrastHighDefault = DBColors.successful6
var bgInvertedContrastHighHovered = DBColors.successful5
var bgInvertedContrastHighPressed = DBColors.successful4
var bgInvertedContrastLowDefault = DBColors.successful7
var bgInvertedContrastLowHovered = DBColors.successful6
var bgInvertedContrastLowPressed = DBColors.successful5
var onBgInvertedDefault = DBColors.successful14
var onBgInvertedHovered = DBColors.successful13
var onBgInvertedPressed = DBColors.successful12
var onOriginDefault = DBColors.successfulOnOriginDefaultLight
var onOriginHovered = DBColors.successfulOnOriginHoveredLight
var onOriginPressed = DBColors.successfulOnOriginPressedLight
var originDefault = DBColors.successfulOriginDefaultLight
var originHovered = DBColors.successfulOriginHoveredLight
var originPressed = DBColors.successfulOriginPressedLight
}
@Observable
class CriticalColorsLight: AdaptiveColors {
var bgBasicLevel1Default = DBColors.critical14
var bgBasicLevel1Hovered = DBColors.critical13
var bgBasicLevel1Pressed = DBColors.critical12
var bgBasicLevel2Default = DBColors.critical13
var bgBasicLevel2Hovered = DBColors.critical12
var bgBasicLevel2Pressed = DBColors.critical11
var bgBasicLevel3Default = DBColors.critical12
var bgBasicLevel3Hovered = DBColors.critical11
var bgBasicLevel3Pressed = DBColors.critical10
var bgBasicTransparentFullDefault = DBColors.critical6.opacity(1)
var bgBasicTransparentSemiDefault = DBColors.critical6.opacity(0.84)
var bgBasicTransparentHovered = DBColors.critical6.opacity(0.76)
var bgBasicTransparentPressed = DBColors.critical6.opacity(0.68)
var onBgBasicEmphasis100Default = DBColors.critical3
var onBgBasicEmphasis100Hovered = DBColors.critical4
var onBgBasicEmphasis100Pressed = DBColors.critical5
var onBgBasicEmphasis90Default = DBColors.critical5
var onBgBasicEmphasis90Hovered = DBColors.critical6
var onBgBasicEmphasis90Pressed = DBColors.critical7
var onBgBasicEmphasis80Default = DBColors.critical6
var onBgBasicEmphasis80Hovered = DBColors.critical5
var onBgBasicEmphasis80Pressed = DBColors.critical4
var onBgBasicEmphasis70Default = DBColors.critical7
var onBgBasicEmphasis70Hovered = DBColors.critical6
var onBgBasicEmphasis70Pressed = DBColors.critical5
var onBgBasicEmphasis60Default = DBColors.critical10
var onBgBasicEmphasis60Hovered = DBColors.critical9
var onBgBasicEmphasis60Pressed = DBColors.critical8
var onBgBasicEmphasis50Default = DBColors.critical9
var onBgBasicEmphasis50Hovered = DBColors.critical8
var onBgBasicEmphasis50Pressed = DBColors.critical7
var bgInvertedContrastMaxDefault = DBColors.critical3
var bgInvertedContrastMaxHovered = DBColors.critical4
var bgInvertedContrastMaxPressed = DBColors.critical5
var bgInvertedContrastHighDefault = DBColors.critical6
var bgInvertedContrastHighHovered = DBColors.critical5
var bgInvertedContrastHighPressed = DBColors.critical4
var bgInvertedContrastLowDefault = DBColors.critical7
var bgInvertedContrastLowHovered = DBColors.critical6
var bgInvertedContrastLowPressed = DBColors.critical5
var onBgInvertedDefault = DBColors.critical14
var onBgInvertedHovered = DBColors.critical13
var onBgInvertedPressed = DBColors.critical12
var onOriginDefault = DBColors.criticalOnOriginDefaultLight
var onOriginHovered = DBColors.criticalOnOriginHoveredLight
var onOriginPressed = DBColors.criticalOnOriginPressedLight
var originDefault = DBColors.criticalOriginDefaultLight
var originHovered = DBColors.criticalOriginHoveredLight
var originPressed = DBColors.criticalOriginPressedLight
}
@Observable
class YellowColorsLight: AdaptiveColors {
var bgBasicLevel1Default = DBColors.yellow14
var bgBasicLevel1Hovered = DBColors.yellow13
var bgBasicLevel1Pressed = DBColors.yellow12
var bgBasicLevel2Default = DBColors.yellow13
var bgBasicLevel2Hovered = DBColors.yellow12
var bgBasicLevel2Pressed = DBColors.yellow11
var bgBasicLevel3Default = DBColors.yellow12
var bgBasicLevel3Hovered = DBColors.yellow11
var bgBasicLevel3Pressed = DBColors.yellow10
var bgBasicTransparentFullDefault = DBColors.yellow6.opacity(1)
var bgBasicTransparentSemiDefault = DBColors.yellow6.opacity(0.84)
var bgBasicTransparentHovered = DBColors.yellow6.opacity(0.76)
var bgBasicTransparentPressed = DBColors.yellow6.opacity(0.68)
var onBgBasicEmphasis100Default = DBColors.yellow3
var onBgBasicEmphasis100Hovered = DBColors.yellow4
var onBgBasicEmphasis100Pressed = DBColors.yellow5
var onBgBasicEmphasis90Default = DBColors.yellow5
var onBgBasicEmphasis90Hovered = DBColors.yellow6
var onBgBasicEmphasis90Pressed = DBColors.yellow7
var onBgBasicEmphasis80Default = DBColors.yellow6
var onBgBasicEmphasis80Hovered = DBColors.yellow5
var onBgBasicEmphasis80Pressed = DBColors.yellow4
var onBgBasicEmphasis70Default = DBColors.yellow7
var onBgBasicEmphasis70Hovered = DBColors.yellow6
var onBgBasicEmphasis70Pressed = DBColors.yellow5
var onBgBasicEmphasis60Default = DBColors.yellow10
var onBgBasicEmphasis60Hovered = DBColors.yellow9
var onBgBasicEmphasis60Pressed = DBColors.yellow8
var onBgBasicEmphasis50Default = DBColors.yellow9
var onBgBasicEmphasis50Hovered = DBColors.yellow8
var onBgBasicEmphasis50Pressed = DBColors.yellow7
var bgInvertedContrastMaxDefault = DBColors.yellow3
var bgInvertedContrastMaxHovered = DBColors.yellow4
var bgInvertedContrastMaxPressed = DBColors.yellow5
var bgInvertedContrastHighDefault = DBColors.yellow6
var bgInvertedContrastHighHovered = DBColors.yellow5
var bgInvertedContrastHighPressed = DBColors.yellow4
var bgInvertedContrastLowDefault = DBColors.yellow7
var bgInvertedContrastLowHovered = DBColors.yellow6
var bgInvertedContrastLowPressed = DBColors.yellow5
var onBgInvertedDefault = DBColors.yellow14
var onBgInvertedHovered = DBColors.yellow13
var onBgInvertedPressed = DBColors.yellow12
var onOriginDefault = DBColors.yellowOnOriginDefaultLight
var onOriginHovered = DBColors.yellowOnOriginHoveredLight
var onOriginPressed = DBColors.yellowOnOriginPressedLight
var originDefault = DBColors.yellowOriginDefaultLight
var originHovered = DBColors.yellowOriginHoveredLight
var originPressed = DBColors.yellowOriginPressedLight
}
@Observable
class OrangeColorsLight: AdaptiveColors {
var bgBasicLevel1Default = DBColors.orange14
var bgBasicLevel1Hovered = DBColors.orange13
var bgBasicLevel1Pressed = DBColors.orange12
var bgBasicLevel2Default = DBColors.orange13
var bgBasicLevel2Hovered = DBColors.orange12
var bgBasicLevel2Pressed = DBColors.orange11
var bgBasicLevel3Default = DBColors.orange12
var bgBasicLevel3Hovered = DBColors.orange11
var bgBasicLevel3Pressed = DBColors.orange10
var bgBasicTransparentFullDefault = DBColors.orange6.opacity(1)
var bgBasicTransparentSemiDefault = DBColors.orange6.opacity(0.84)
var bgBasicTransparentHovered = DBColors.orange6.opacity(0.76)
var bgBasicTransparentPressed = DBColors.orange6.opacity(0.68)
var onBgBasicEmphasis100Default = DBColors.orange3
var onBgBasicEmphasis100Hovered = DBColors.orange4
var onBgBasicEmphasis100Pressed = DBColors.orange5
var onBgBasicEmphasis90Default = DBColors.orange5
var onBgBasicEmphasis90Hovered = DBColors.orange6
var onBgBasicEmphasis90Pressed = DBColors.orange7
var onBgBasicEmphasis80Default = DBColors.orange6
var onBgBasicEmphasis80Hovered = DBColors.orange5
var onBgBasicEmphasis80Pressed = DBColors.orange4
var onBgBasicEmphasis70Default = DBColors.orange7
var onBgBasicEmphasis70Hovered = DBColors.orange6
var onBgBasicEmphasis70Pressed = DBColors.orange5
var onBgBasicEmphasis60Default = DBColors.orange10
var onBgBasicEmphasis60Hovered = DBColors.orange9
var onBgBasicEmphasis60Pressed = DBColors.orange8
var onBgBasicEmphasis50Default = DBColors.orange9
var onBgBasicEmphasis50Hovered = DBColors.orange8
var onBgBasicEmphasis50Pressed = DBColors.orange7
var bgInvertedContrastMaxDefault = DBColors.orange3
var bgInvertedContrastMaxHovered = DBColors.orange4
var bgInvertedContrastMaxPressed = DBColors.orange5
var bgInvertedContrastHighDefault = DBColors.orange6
var bgInvertedContrastHighHovered = DBColors.orange5
var bgInvertedContrastHighPressed = DBColors.orange4
var bgInvertedContrastLowDefault = DBColors.orange7
var bgInvertedContrastLowHovered = DBColors.orange6
var bgInvertedContrastLowPressed = DBColors.orange5
var onBgInvertedDefault = DBColors.orange14
var onBgInvertedHovered = DBColors.orange13
var onBgInvertedPressed = DBColors.orange12
var onOriginDefault = DBColors.orangeOnOriginDefaultLight
var onOriginHovered = DBColors.orangeOnOriginHoveredLight
var onOriginPressed = DBColors.orangeOnOriginPressedLight
var originDefault = DBColors.orangeOriginDefaultLight
var originHovered = DBColors.orangeOriginHoveredLight
var originPressed = DBColors.orangeOriginPressedLight
}
@Observable
class RedColorsLight: AdaptiveColors {
var bgBasicLevel1Default = DBColors.red14
var bgBasicLevel1Hovered = DBColors.red13
var bgBasicLevel1Pressed = DBColors.red12
var bgBasicLevel2Default = DBColors.red13
var bgBasicLevel2Hovered = DBColors.red12
var bgBasicLevel2Pressed = DBColors.red11
var bgBasicLevel3Default = DBColors.red12
var bgBasicLevel3Hovered = DBColors.red11
var bgBasicLevel3Pressed = DBColors.red10
var bgBasicTransparentFullDefault = DBColors.red6.opacity(1)
var bgBasicTransparentSemiDefault = DBColors.red6.opacity(0.84)
var bgBasicTransparentHovered = DBColors.red6.opacity(0.76)
var bgBasicTransparentPressed = DBColors.red6.opacity(0.68)
var onBgBasicEmphasis100Default = DBColors.red3
var onBgBasicEmphasis100Hovered = DBColors.red4
var onBgBasicEmphasis100Pressed = DBColors.red5
var onBgBasicEmphasis90Default = DBColors.red5
var onBgBasicEmphasis90Hovered = DBColors.red6
var onBgBasicEmphasis90Pressed = DBColors.red7
var onBgBasicEmphasis80Default = DBColors.red6
var onBgBasicEmphasis80Hovered = DBColors.red5
var onBgBasicEmphasis80Pressed = DBColors.red4
var onBgBasicEmphasis70Default = DBColors.red7
var onBgBasicEmphasis70Hovered = DBColors.red6
var onBgBasicEmphasis70Pressed = DBColors.red5
var onBgBasicEmphasis60Default = DBColors.red10
var onBgBasicEmphasis60Hovered = DBColors.red9
var onBgBasicEmphasis60Pressed = DBColors.red8
var onBgBasicEmphasis50Default = DBColors.red9
var onBgBasicEmphasis50Hovered = DBColors.red8
var onBgBasicEmphasis50Pressed = DBColors.red7
var bgInvertedContrastMaxDefault = DBColors.red3
var bgInvertedContrastMaxHovered = DBColors.red4
var bgInvertedContrastMaxPressed = DBColors.red5
var bgInvertedContrastHighDefault = DBColors.red6
var bgInvertedContrastHighHovered = DBColors.red5
var bgInvertedContrastHighPressed = DBColors.red4
var bgInvertedContrastLowDefault = DBColors.red7
var bgInvertedContrastLowHovered = DBColors.red6
var bgInvertedContrastLowPressed = DBColors.red5
var onBgInvertedDefault = DBColors.red14
var onBgInvertedHovered = DBColors.red13
var onBgInvertedPressed = DBColors.red12
var onOriginDefault = DBColors.redOnOriginDefaultLight
var onOriginHovered = DBColors.redOnOriginHoveredLight
var onOriginPressed = DBColors.redOnOriginPressedLight
var originDefault = DBColors.redOriginDefaultLight
var originHovered = DBColors.redOriginHoveredLight
var originPressed = DBColors.redOriginPressedLight
}
@Observable
class PinkColorsLight: AdaptiveColors {
var bgBasicLevel1Default = DBColors.pink14
var bgBasicLevel1Hovered = DBColors.pink13
var bgBasicLevel1Pressed = DBColors.pink12
var bgBasicLevel2Default = DBColors.pink13
var bgBasicLevel2Hovered = DBColors.pink12
var bgBasicLevel2Pressed = DBColors.pink11
var bgBasicLevel3Default = DBColors.pink12
var bgBasicLevel3Hovered = DBColors.pink11
var bgBasicLevel3Pressed = DBColors.pink10
var bgBasicTransparentFullDefault = DBColors.pink6.opacity(1)
var bgBasicTransparentSemiDefault = DBColors.pink6.opacity(0.84)
var bgBasicTransparentHovered = DBColors.pink6.opacity(0.76)
var bgBasicTransparentPressed = DBColors.pink6.opacity(0.68)
var onBgBasicEmphasis100Default = DBColors.pink3
var onBgBasicEmphasis100Hovered = DBColors.pink4
var onBgBasicEmphasis100Pressed = DBColors.pink5
var onBgBasicEmphasis90Default = DBColors.pink5
var onBgBasicEmphasis90Hovered = DBColors.pink6
var onBgBasicEmphasis90Pressed = DBColors.pink7
var onBgBasicEmphasis80Default = DBColors.pink6
var onBgBasicEmphasis80Hovered = DBColors.pink5
var onBgBasicEmphasis80Pressed = DBColors.pink4
var onBgBasicEmphasis70Default = DBColors.pink7
var onBgBasicEmphasis70Hovered = DBColors.pink6
var onBgBasicEmphasis70Pressed = DBColors.pink5
var onBgBasicEmphasis60Default = DBColors.pink10
var onBgBasicEmphasis60Hovered = DBColors.pink9
var onBgBasicEmphasis60Pressed = DBColors.pink8
var onBgBasicEmphasis50Default = DBColors.pink9
var onBgBasicEmphasis50Hovered = DBColors.pink8
var onBgBasicEmphasis50Pressed = DBColors.pink7
var bgInvertedContrastMaxDefault = DBColors.pink3
var bgInvertedContrastMaxHovered = DBColors.pink4
var bgInvertedContrastMaxPressed = DBColors.pink5
var bgInvertedContrastHighDefault = DBColors.pink6
var bgInvertedContrastHighHovered = DBColors.pink5
var bgInvertedContrastHighPressed = DBColors.pink4
var bgInvertedContrastLowDefault = DBColors.pink7
var bgInvertedContrastLowHovered = DBColors.pink6
var bgInvertedContrastLowPressed = DBColors.pink5
var onBgInvertedDefault = DBColors.pink14
var onBgInvertedHovered = DBColors.pink13
var onBgInvertedPressed = DBColors.pink12
var onOriginDefault = DBColors.pinkOnOriginDefaultLight
var onOriginHovered = DBColors.pinkOnOriginHoveredLight
var onOriginPressed = DBColors.pinkOnOriginPressedLight
var originDefault = DBColors.pinkOriginDefaultLight
var originHovered = DBColors.pinkOriginHoveredLight
var originPressed = DBColors.pinkOriginPressedLight
}
@Observable
class VioletColorsLight: AdaptiveColors {
var bgBasicLevel1Default = DBColors.violet14
var bgBasicLevel1Hovered = DBColors.violet13
var bgBasicLevel1Pressed = DBColors.violet12
var bgBasicLevel2Default = DBColors.violet13
var bgBasicLevel2Hovered = DBColors.violet12
var bgBasicLevel2Pressed = DBColors.violet11
var bgBasicLevel3Default = DBColors.violet12
var bgBasicLevel3Hovered = DBColors.violet11
var bgBasicLevel3Pressed = DBColors.violet10
var bgBasicTransparentFullDefault = DBColors.violet6.opacity(1)
var bgBasicTransparentSemiDefault = DBColors.violet6.opacity(0.84)
var bgBasicTransparentHovered = DBColors.violet6.opacity(0.76)
var bgBasicTransparentPressed = DBColors.violet6.opacity(0.68)
var onBgBasicEmphasis100Default = DBColors.violet3
var onBgBasicEmphasis100Hovered = DBColors.violet4
var onBgBasicEmphasis100Pressed = DBColors.violet5
var onBgBasicEmphasis90Default = DBColors.violet5
var onBgBasicEmphasis90Hovered = DBColors.violet6
var onBgBasicEmphasis90Pressed = DBColors.violet7
var onBgBasicEmphasis80Default = DBColors.violet6
var onBgBasicEmphasis80Hovered = DBColors.violet5
var onBgBasicEmphasis80Pressed = DBColors.violet4
var onBgBasicEmphasis70Default = DBColors.violet7
var onBgBasicEmphasis70Hovered = DBColors.violet6
var onBgBasicEmphasis70Pressed = DBColors.violet5
var onBgBasicEmphasis60Default = DBColors.violet10
var onBgBasicEmphasis60Hovered = DBColors.violet9
var onBgBasicEmphasis60Pressed = DBColors.violet8
var onBgBasicEmphasis50Default = DBColors.violet9
var onBgBasicEmphasis50Hovered = DBColors.violet8
var onBgBasicEmphasis50Pressed = DBColors.violet7
var bgInvertedContrastMaxDefault = DBColors.violet3
var bgInvertedContrastMaxHovered = DBColors.violet4
var bgInvertedContrastMaxPressed = DBColors.violet5
var bgInvertedContrastHighDefault = DBColors.violet6
var bgInvertedContrastHighHovered = DBColors.violet5
var bgInvertedContrastHighPressed = DBColors.violet4
var bgInvertedContrastLowDefault = DBColors.violet7
var bgInvertedContrastLowHovered = DBColors.violet6
var bgInvertedContrastLowPressed = DBColors.violet5
var onBgInvertedDefault = DBColors.violet14
var onBgInvertedHovered = DBColors.violet13
var onBgInvertedPressed = DBColors.violet12
var onOriginDefault = DBColors.violetOnOriginDefaultLight
var onOriginHovered = DBColors.violetOnOriginHoveredLight
var onOriginPressed = DBColors.violetOnOriginPressedLight
var originDefault = DBColors.violetOriginDefaultLight
var originHovered = DBColors.violetOriginHoveredLight
var originPressed = DBColors.violetOriginPressedLight
}
@Observable
class BlueColorsLight: AdaptiveColors {
var bgBasicLevel1Default = DBColors.blue14
var bgBasicLevel1Hovered = DBColors.blue13
var bgBasicLevel1Pressed = DBColors.blue12
var bgBasicLevel2Default = DBColors.blue13
var bgBasicLevel2Hovered = DBColors.blue12
var bgBasicLevel2Pressed = DBColors.blue11
var bgBasicLevel3Default = DBColors.blue12
var bgBasicLevel3Hovered = DBColors.blue11
var bgBasicLevel3Pressed = DBColors.blue10
var bgBasicTransparentFullDefault = DBColors.blue6.opacity(1)
var bgBasicTransparentSemiDefault = DBColors.blue6.opacity(0.84)
var bgBasicTransparentHovered = DBColors.blue6.opacity(0.76)
var bgBasicTransparentPressed = DBColors.blue6.opacity(0.68)
var onBgBasicEmphasis100Default = DBColors.blue3
var onBgBasicEmphasis100Hovered = DBColors.blue4
var onBgBasicEmphasis100Pressed = DBColors.blue5
var onBgBasicEmphasis90Default = DBColors.blue5
var onBgBasicEmphasis90Hovered = DBColors.blue6
var onBgBasicEmphasis90Pressed = DBColors.blue7
var onBgBasicEmphasis80Default = DBColors.blue6
var onBgBasicEmphasis80Hovered = DBColors.blue5
var onBgBasicEmphasis80Pressed = DBColors.blue4
var onBgBasicEmphasis70Default = DBColors.blue7
var onBgBasicEmphasis70Hovered = DBColors.blue6
var onBgBasicEmphasis70Pressed = DBColors.blue5
var onBgBasicEmphasis60Default = DBColors.blue10
var onBgBasicEmphasis60Hovered = DBColors.blue9
var onBgBasicEmphasis60Pressed = DBColors.blue8
var onBgBasicEmphasis50Default = DBColors.blue9
var onBgBasicEmphasis50Hovered = DBColors.blue8
var onBgBasicEmphasis50Pressed = DBColors.blue7
var bgInvertedContrastMaxDefault = DBColors.blue3
var bgInvertedContrastMaxHovered = DBColors.blue4
var bgInvertedContrastMaxPressed = DBColors.blue5
var bgInvertedContrastHighDefault = DBColors.blue6
var bgInvertedContrastHighHovered = DBColors.blue5
var bgInvertedContrastHighPressed = DBColors.blue4
var bgInvertedContrastLowDefault = DBColors.blue7
var bgInvertedContrastLowHovered = DBColors.blue6
var bgInvertedContrastLowPressed = DBColors.blue5
var onBgInvertedDefault = DBColors.blue14
var onBgInvertedHovered = DBColors.blue13
var onBgInvertedPressed = DBColors.blue12
var onOriginDefault = DBColors.blueOnOriginDefaultLight
var onOriginHovered = DBColors.blueOnOriginHoveredLight
var onOriginPressed = DBColors.blueOnOriginPressedLight
var originDefault = DBColors.blueOriginDefaultLight
var originHovered = DBColors.blueOriginHoveredLight
var originPressed = DBColors.blueOriginPressedLight
}
@Observable
class CyanColorsLight: AdaptiveColors {
var bgBasicLevel1Default = DBColors.cyan14
var bgBasicLevel1Hovered = DBColors.cyan13
var bgBasicLevel1Pressed = DBColors.cyan12
var bgBasicLevel2Default = DBColors.cyan13
var bgBasicLevel2Hovered = DBColors.cyan12
var bgBasicLevel2Pressed = DBColors.cyan11
var bgBasicLevel3Default = DBColors.cyan12
var bgBasicLevel3Hovered = DBColors.cyan11
var bgBasicLevel3Pressed = DBColors.cyan10
var bgBasicTransparentFullDefault = DBColors.cyan6.opacity(1)
var bgBasicTransparentSemiDefault = DBColors.cyan6.opacity(0.84)
var bgBasicTransparentHovered = DBColors.cyan6.opacity(0.76)
var bgBasicTransparentPressed = DBColors.cyan6.opacity(0.68)
var onBgBasicEmphasis100Default = DBColors.cyan3
var onBgBasicEmphasis100Hovered = DBColors.cyan4
var onBgBasicEmphasis100Pressed = DBColors.cyan5
var onBgBasicEmphasis90Default = DBColors.cyan5
var onBgBasicEmphasis90Hovered = DBColors.cyan6
var onBgBasicEmphasis90Pressed = DBColors.cyan7
var onBgBasicEmphasis80Default = DBColors.cyan6
var onBgBasicEmphasis80Hovered = DBColors.cyan5
var onBgBasicEmphasis80Pressed = DBColors.cyan4
var onBgBasicEmphasis70Default = DBColors.cyan7
var onBgBasicEmphasis70Hovered = DBColors.cyan6
var onBgBasicEmphasis70Pressed = DBColors.cyan5
var onBgBasicEmphasis60Default = DBColors.cyan10
var onBgBasicEmphasis60Hovered = DBColors.cyan9
var onBgBasicEmphasis60Pressed = DBColors.cyan8
var onBgBasicEmphasis50Default = DBColors.cyan9
var onBgBasicEmphasis50Hovered = DBColors.cyan8
var onBgBasicEmphasis50Pressed = DBColors.cyan7
var bgInvertedContrastMaxDefault = DBColors.cyan3
var bgInvertedContrastMaxHovered = DBColors.cyan4
var bgInvertedContrastMaxPressed = DBColors.cyan5
var bgInvertedContrastHighDefault = DBColors.cyan6
var bgInvertedContrastHighHovered = DBColors.cyan5
var bgInvertedContrastHighPressed = DBColors.cyan4
var bgInvertedContrastLowDefault = DBColors.cyan7
var bgInvertedContrastLowHovered = DBColors.cyan6
var bgInvertedContrastLowPressed = DBColors.cyan5
var onBgInvertedDefault = DBColors.cyan14
var onBgInvertedHovered = DBColors.cyan13
var onBgInvertedPressed = DBColors.cyan12
var onOriginDefault = DBColors.cyanOnOriginDefaultLight
var onOriginHovered = DBColors.cyanOnOriginHoveredLight
var onOriginPressed = DBColors.cyanOnOriginPressedLight
var originDefault = DBColors.cyanOriginDefaultLight
var originHovered = DBColors.cyanOriginHoveredLight
var originPressed = DBColors.cyanOriginPressedLight
}
@Observable
class TurquoiseColorsLight: AdaptiveColors {
var bgBasicLevel1Default = DBColors.turquoise14
var bgBasicLevel1Hovered = DBColors.turquoise13
var bgBasicLevel1Pressed = DBColors.turquoise12
var bgBasicLevel2Default = DBColors.turquoise13
var bgBasicLevel2Hovered = DBColors.turquoise12
var bgBasicLevel2Pressed = DBColors.turquoise11
var bgBasicLevel3Default = DBColors.turquoise12
var bgBasicLevel3Hovered = DBColors.turquoise11
var bgBasicLevel3Pressed = DBColors.turquoise10
var bgBasicTransparentFullDefault = DBColors.turquoise6.opacity(1)
var bgBasicTransparentSemiDefault = DBColors.turquoise6.opacity(0.84)
var bgBasicTransparentHovered = DBColors.turquoise6.opacity(0.76)
var bgBasicTransparentPressed = DBColors.turquoise6.opacity(0.68)
var onBgBasicEmphasis100Default = DBColors.turquoise3
var onBgBasicEmphasis100Hovered = DBColors.turquoise4
var onBgBasicEmphasis100Pressed = DBColors.turquoise5
var onBgBasicEmphasis90Default = DBColors.turquoise5
var onBgBasicEmphasis90Hovered = DBColors.turquoise6
var onBgBasicEmphasis90Pressed = DBColors.turquoise7
var onBgBasicEmphasis80Default = DBColors.turquoise6
var onBgBasicEmphasis80Hovered = DBColors.turquoise5
var onBgBasicEmphasis80Pressed = DBColors.turquoise4
var onBgBasicEmphasis70Default = DBColors.turquoise7
var onBgBasicEmphasis70Hovered = DBColors.turquoise6
var onBgBasicEmphasis70Pressed = DBColors.turquoise5
var onBgBasicEmphasis60Default = DBColors.turquoise10
var onBgBasicEmphasis60Hovered = DBColors.turquoise9
var onBgBasicEmphasis60Pressed = DBColors.turquoise8
var onBgBasicEmphasis50Default = DBColors.turquoise9
var onBgBasicEmphasis50Hovered = DBColors.turquoise8
var onBgBasicEmphasis50Pressed = DBColors.turquoise7
var bgInvertedContrastMaxDefault = DBColors.turquoise3
var bgInvertedContrastMaxHovered = DBColors.turquoise4
var bgInvertedContrastMaxPressed = DBColors.turquoise5
var bgInvertedContrastHighDefault = DBColors.turquoise6
var bgInvertedContrastHighHovered = DBColors.turquoise5
var bgInvertedContrastHighPressed = DBColors.turquoise4
var bgInvertedContrastLowDefault = DBColors.turquoise7
var bgInvertedContrastLowHovered = DBColors.turquoise6
var bgInvertedContrastLowPressed = DBColors.turquoise5
var onBgInvertedDefault = DBColors.turquoise14
var onBgInvertedHovered = DBColors.turquoise13
var onBgInvertedPressed = DBColors.turquoise12
var onOriginDefault = DBColors.turquoiseOnOriginDefaultLight
var onOriginHovered = DBColors.turquoiseOnOriginHoveredLight
var onOriginPressed = DBColors.turquoiseOnOriginPressedLight
var originDefault = DBColors.turquoiseOriginDefaultLight
var originHovered = DBColors.turquoiseOriginHoveredLight
var originPressed = DBColors.turquoiseOriginPressedLight
}
@Observable
class GreenColorsLight: AdaptiveColors {
var bgBasicLevel1Default = DBColors.green14
var bgBasicLevel1Hovered = DBColors.green13
var bgBasicLevel1Pressed = DBColors.green12
var bgBasicLevel2Default = DBColors.green13
var bgBasicLevel2Hovered = DBColors.green12
var bgBasicLevel2Pressed = DBColors.green11
var bgBasicLevel3Default = DBColors.green12
var bgBasicLevel3Hovered = DBColors.green11
var bgBasicLevel3Pressed = DBColors.green10
var bgBasicTransparentFullDefault = DBColors.green6.opacity(1)
var bgBasicTransparentSemiDefault = DBColors.green6.opacity(0.84)
var bgBasicTransparentHovered = DBColors.green6.opacity(0.76)
var bgBasicTransparentPressed = DBColors.green6.opacity(0.68)
var onBgBasicEmphasis100Default = DBColors.green3
var onBgBasicEmphasis100Hovered = DBColors.green4
var onBgBasicEmphasis100Pressed = DBColors.green5
var onBgBasicEmphasis90Default = DBColors.green5
var onBgBasicEmphasis90Hovered = DBColors.green6
var onBgBasicEmphasis90Pressed = DBColors.green7
var onBgBasicEmphasis80Default = DBColors.green6
var onBgBasicEmphasis80Hovered = DBColors.green5
var onBgBasicEmphasis80Pressed = DBColors.green4
var onBgBasicEmphasis70Default = DBColors.green7
var onBgBasicEmphasis70Hovered = DBColors.green6
var onBgBasicEmphasis70Pressed = DBColors.green5
var onBgBasicEmphasis60Default = DBColors.green10
var onBgBasicEmphasis60Hovered = DBColors.green9
var onBgBasicEmphasis60Pressed = DBColors.green8
var onBgBasicEmphasis50Default = DBColors.green9
var onBgBasicEmphasis50Hovered = DBColors.green8
var onBgBasicEmphasis50Pressed = DBColors.green7
var bgInvertedContrastMaxDefault = DBColors.green3
var bgInvertedContrastMaxHovered = DBColors.green4
var bgInvertedContrastMaxPressed = DBColors.green5
var bgInvertedContrastHighDefault = DBColors.green6
var bgInvertedContrastHighHovered = DBColors.green5
var bgInvertedContrastHighPressed = DBColors.green4
var bgInvertedContrastLowDefault = DBColors.green7
var bgInvertedContrastLowHovered = DBColors.green6
var bgInvertedContrastLowPressed = DBColors.green5
var onBgInvertedDefault = DBColors.green14
var onBgInvertedHovered = DBColors.green13
var onBgInvertedPressed = DBColors.green12
var onOriginDefault = DBColors.greenOnOriginDefaultLight
var onOriginHovered = DBColors.greenOnOriginHoveredLight
var onOriginPressed = DBColors.greenOnOriginPressedLight
var originDefault = DBColors.greenOriginDefaultLight
var originHovered = DBColors.greenOriginHoveredLight
var originPressed = DBColors.greenOriginPressedLight
}
func getColorSchemeLight(
neutral: AdaptiveColors = NeutralColorsLight(),
brand: AdaptiveColors = BrandColorsLight(),
informational: AdaptiveColors = InformationalColorsLight(),
warning: AdaptiveColors = WarningColorsLight(),
successful: AdaptiveColors = SuccessfulColorsLight(),
critical: AdaptiveColors = CriticalColorsLight(),
yellow: AdaptiveColors = YellowColorsLight(),
orange: AdaptiveColors = OrangeColorsLight(),
red: AdaptiveColors = RedColorsLight(),
pink: AdaptiveColors = PinkColorsLight(),
violet: AdaptiveColors = VioletColorsLight(),
blue: AdaptiveColors = BlueColorsLight(),
cyan: AdaptiveColors = CyanColorsLight(),
turquoise: AdaptiveColors = TurquoiseColorsLight(),
green: AdaptiveColors = GreenColorsLight()
) -> DeutscheBahnThemeColorScheme { 
   DeutscheBahnThemeColorScheme(
neutral: neutral,
brand: brand,
informational: informational,
warning: warning,
successful: successful,
critical: critical,
yellow: yellow,
orange: orange,
red: red,
pink: pink,
violet: violet,
blue: blue,
cyan: cyan,
turquoise: turquoise,
green: green)
}
